package ProjectEuler;

/**
 * 
 * @author Bharat
 *
 */
/**
 * 
 * Each new terms in fibonacci seuence is generated by adding the previous two terms. By
 * startng with 1 and 2, the first 10 terms will be:
 * 
 *  <p> By considering the terms in the fbonacci sequence whose values do not exceed four million,
 *  fnd the sum of the even-valued terms 
 *
 */
public class Probelem2 {
	public static void main(String[] args)
	{
		int [][] testNumber = {
				{10,20},
				{15,10},
				{2,2},
				{1,0},
				{89,44},
		};
		
		for(int[] ints : testNumber)
		{
			assert solution1(ints[0]) == ints[1];
		}
	}
	
	private static int solution1(int n)
	{
		int sum = 0;
		int first = 1;
		int second = 2;
		while (second <= n)
		{
			if(second % 2 == 0)
			{
				sum += second;
			}
			int temp = first + second;
			first = second;
			second = temp;
		}
		return sum;
	}

}
